export const CHANGE_BANNER = 'recommend/CHANGE_BANNER';
export type CHANGE_BANNER = typeof CHANGE_BANNER;

export const CHANGE_RECOMMEND_LIST = 'recommend/CHANGE_RECOMMEND_LIST';
export type CHANGE_RECOMMEND_LIST = typeof CHANGE_RECOMMEND_LIST;

export const CHANGE_ENTER_LOADING = 'recommend/CHANGE_ENTER_LOADING';
export type CHANGE_ENTER_LOADING = typeof CHANGE_ENTER_LOADING;